name: Publish

on:
  push:
    tags: 
      - '*'

jobs:
  build:
    name: Publish
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        run: cargo publish --token ${{ secrets.cratesio_token }}
